# Generated by Django 5.2.4 on 2025-09-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='herione',
            new_name='heroine',
        ),
    ]
